#!/usr/bin/env python3
"""
Load SBI priors from CSV file and create a torch MultipleIndependent prior.

Reads a CSV file with parameter distributions (generated by generate_sbi_priors.py)
and constructs a sbi.utils.MultipleIndependent prior for use with SBI workflows.

CSV format:
    name, expected_value, units, distribution, dist_param1, dist_param2, lower_bound, upper_bound

    Note: lower_bound and upper_bound are optional columns (backward compatible).
          Leave empty or omit columns for unbounded distributions.

Supported distributions:
    - lognormal: dist_param1=μ (log mean), dist_param2=σ (log std)
    - normal: dist_param1=mean, dist_param2=std
    - uniform: dist_param1=lower, dist_param2=upper
    - beta: dist_param1=alpha, dist_param2=beta

Truncation bounds (optional):
    - lower_bound: Minimum value (inclusive) in original parameter space
    - upper_bound: Maximum value (inclusive) in original parameter space
    - Both, either, or neither can be specified
    - Bounds are applied via rejection sampling

Usage:
    from qsp_inference.priors import load_prior, get_param_names, transform_lognormal_prior_to_normal

    prior = load_prior('projects/pdac_2025/cache/pdac_sbi_priors.csv')
    param_names = get_param_names('projects/pdac_2025/cache/pdac_sbi_priors.csv')

    # Transform to normal space for log-transformed parameters
    prior_normal = transform_lognormal_prior_to_normal(prior)
"""

import csv
import torch
from pathlib import Path
from typing import Union, List, Optional
from torch.distributions import Normal, LogNormal, Uniform, Beta
from sbi.utils import MultipleIndependent
from qsp_inference.priors.truncated_distributions import TruncatedDistribution


def _parse_bound(value: str, bound_name: str, param_name: str) -> Optional[float]:
    """
    Parse a bound value from CSV.

    Args:
        value: String value from CSV (may be empty)
        bound_name: Name of the bound ('lower_bound' or 'upper_bound') for error messages
        param_name: Parameter name for error messages

    Returns:
        Float value if bound is specified, None otherwise

    Raises:
        ValueError: If bound is present but cannot be parsed as float
    """
    if not value or value.strip() == '':
        return None

    try:
        return float(value.strip())
    except ValueError:
        raise ValueError(
            f"Invalid {bound_name} '{value}' for parameter '{param_name}'. "
            f"Must be a number or empty."
        )


def get_param_names(csv_path: Union[str, Path]) -> List[str]:
    """
    Load parameter names from prior CSV file.

    Args:
        csv_path: Path to CSV file with prior specifications

    Returns:
        List of parameter names in the order they appear in the CSV
    """
    csv_path = Path(csv_path)

    if not csv_path.exists():
        raise FileNotFoundError(f"Prior CSV file not found: {csv_path}")

    param_names = []

    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            param_names.append(row['name'])

    return param_names


def load_prior(csv_path: Union[str, Path], device: str = "cpu") -> MultipleIndependent:
    """
    Load prior distributions from CSV file.

    Args:
        csv_path: Path to CSV file with prior specifications
        device: Torch device to use ('cpu' or 'cuda')

    Returns:
        MultipleIndependent prior object
    """
    csv_path = Path(csv_path)

    if not csv_path.exists():
        raise FileNotFoundError(f"Prior CSV file not found: {csv_path}")

    distributions = []

    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)

        # Check if bounds columns exist (for backward compatibility)
        has_bounds_columns = 'lower_bound' in reader.fieldnames or 'upper_bound' in reader.fieldnames

        for row in reader:
            param_name = row['name']
            dist_type = row['distribution'].strip().lower()
            param1 = float(row['dist_param1'])
            param2 = float(row['dist_param2'])

            # Create base distribution
            if dist_type == 'lognormal':
                dist = LogNormal(
                    loc=torch.tensor([param1], device=device),
                    scale=torch.tensor([param2], device=device)
                )
            elif dist_type == 'normal':
                dist = Normal(
                    loc=torch.tensor([param1], device=device),
                    scale=torch.tensor([param2], device=device)
                )
            elif dist_type == 'uniform':
                dist = Uniform(
                    low=torch.tensor([param1], device=device),
                    high=torch.tensor([param2], device=device)
                )
            elif dist_type == 'beta':
                dist = Beta(
                    concentration1=torch.tensor([param1], device=device),
                    concentration0=torch.tensor([param2], device=device)
                )
            else:
                raise ValueError(
                    f"Unknown distribution type '{dist_type}' for parameter '{param_name}'"
                )

            # Apply truncation bounds if specified
            if has_bounds_columns:
                lower_bound = _parse_bound(
                    row.get('lower_bound', ''), 'lower_bound', param_name
                )
                upper_bound = _parse_bound(
                    row.get('upper_bound', ''), 'upper_bound', param_name
                )

                # Validate bounds
                if lower_bound is not None and upper_bound is not None:
                    if lower_bound >= upper_bound:
                        raise ValueError(
                            f"Invalid bounds for parameter '{param_name}': "
                            f"lower_bound ({lower_bound}) must be less than "
                            f"upper_bound ({upper_bound})"
                        )

                # Additional validation for specific distribution types
                if dist_type == 'lognormal' and lower_bound is not None:
                    if lower_bound <= 0:
                        raise ValueError(
                            f"Invalid lower_bound for lognormal parameter '{param_name}': "
                            f"must be positive, got {lower_bound}"
                        )

                if dist_type == 'beta':
                    if lower_bound is not None and (lower_bound < 0 or lower_bound > 1):
                        raise ValueError(
                            f"Invalid lower_bound for beta parameter '{param_name}': "
                            f"must be in [0, 1], got {lower_bound}"
                        )
                    if upper_bound is not None and (upper_bound < 0 or upper_bound > 1):
                        raise ValueError(
                            f"Invalid upper_bound for beta parameter '{param_name}': "
                            f"must be in [0, 1], got {upper_bound}"
                        )

                # Wrap with truncated distribution if bounds are specified
                if lower_bound is not None or upper_bound is not None:
                    dist = TruncatedDistribution(
                        dist, low=lower_bound, high=upper_bound
                    )

            distributions.append(dist)

    if not distributions:
        raise ValueError(f"No distributions found in CSV file: {csv_path}")

    return MultipleIndependent(distributions)


def transform_lognormal_prior_to_normal(lognormal_prior: MultipleIndependent) -> MultipleIndependent:
    """
    Transform a MultipleIndependent of LogNormal distributions to Normal distributions.

    When parameters are log-transformed, LogNormal(μ, σ) in original space
    becomes Normal(μ, σ) in log space, where μ and σ are the parameters of
    the underlying normal distribution.

    Handles both:
    - Plain LogNormal distributions
    - TruncatedDistribution wrappers around LogNormal (bounds are transformed to log-space)

    Args:
        lognormal_prior: sbi.utils.MultipleIndependent with LogNormal distributions
                        (optionally wrapped in TruncatedDistribution)

    Returns:
        normal_prior: MultipleIndependent with Normal distributions in log space
                     (with transformed truncation bounds if applicable)

    Example:
        >>> prior_lognormal = load_prior('priors.csv')  # LogNormal distributions
        >>> prior_normal = transform_lognormal_prior_to_normal(prior_lognormal)
        >>> # Now use prior_normal for inference with log-transformed parameters
    """
    import math

    if not hasattr(lognormal_prior, 'dists'):
        raise ValueError("Prior must be a MultipleIndependent distribution")

    # Transform each LogNormal to Normal
    normal_dists = []
    for d in lognormal_prior.dists:
        # Check if this is a truncated distribution
        if isinstance(d, TruncatedDistribution):
            base_dist = d.base_distribution
            has_lower = d.has_lower
            has_upper = d.has_upper

            if not isinstance(base_dist, LogNormal):
                raise ValueError(
                    f"Expected LogNormal base distribution in TruncatedDistribution, "
                    f"got {type(base_dist)}"
                )

            # Create Normal distribution with same loc/scale
            normal_dist = Normal(base_dist.loc, base_dist.scale)

            # Transform bounds to log-space
            # If x ~ LogNormal(μ, σ), then log(x) ~ Normal(μ, σ)
            # So bounds [a, b] in original space become [log(a), log(b)] in log-space
            log_low = math.log(d.low) if has_lower and d.low > 0 else None
            log_high = math.log(d.high) if has_upper and d.high > 0 else None

            # Wrap in truncated distribution with transformed bounds
            if log_low is not None or log_high is not None:
                normal_dists.append(TruncatedDistribution(normal_dist, low=log_low, high=log_high))
            else:
                normal_dists.append(normal_dist)

        elif isinstance(d, LogNormal):
            # Plain LogNormal without truncation
            # LogNormal has parameters: loc (μ) and scale (σ)
            # These are the mean and std of the underlying normal
            normal_dists.append(Normal(d.loc, d.scale))
        else:
            raise ValueError(f"Expected LogNormal distribution, got {type(d)}")

    return MultipleIndependent(normal_dists)
